// Code generated by hertz generator.

package order_page

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
