// Code generated by hertz generator.

package cart_page

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addcartitemMw() []app.HandlerFunc {
	// your code...
	return nil
}
